// Bundles the viewer (TS + CSS) into a single generated TS module that exports
// the JS and CSS as strings. These get inlined into the output HTML by the CLI,
// so the produced file has ZERO external requests.
import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const result = await build({
  entryPoints: [resolve(root, "src/viewer/app.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2019",
  write: false,
  legalComments: "none",
});
const js = result.outputFiles[0].text;
const css = await readFile(resolve(root, "src/viewer/styles.css"), "utf8");

// Cheap CSS minify (safe: collapse whitespace, strip comments).
const cssMin = css
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/\s+/g, " ")
  .replace(/\s*([{}:;,>])\s*/g, "$1")
  .replace(/;}/g, "}")
  .trim();

const enc = (s) => JSON.stringify(s);
const out = `// AUTO-GENERATED by scripts/build-viewer.mjs — do not edit.
export const VIEWER_JS = ${enc(js)};
export const VIEWER_CSS = ${enc(cssMin)};
`;

await mkdir(resolve(root, "src/generated"), { recursive: true });
await writeFile(resolve(root, "src/generated/viewer-assets.ts"), out);
console.log(`viewer built: js ${(js.length / 1024).toFixed(1)}kb, css ${(cssMin.length / 1024).toFixed(1)}kb`);
